# -*- coding: utf-8 -*-
"""Backtesting vs VNINDEX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zIV7l7z0H5UhzAdRQRt763-Aek_G2q7D
"""

from google.colab import files
uploaded = files.upload()

file_path = list(uploaded.keys())[0]
print(file_path)

import pandas as pd
import numpy as np
from scipy import stats

xls = pd.ExcelFile(file_path)
print(xls.sheet_names)

PORTFOLIO_SHEET = "portfolio"
PRICES_SHEET = "price"
VNINDEX_SHEET = "vnindex"

portfolio = pd.read_excel(file_path, sheet_name=PORTFOLIO_SHEET)
prices = pd.read_excel(file_path, sheet_name=PRICES_SHEET)
vnindex = pd.read_excel(file_path, sheet_name=VNINDEX_SHEET)

print(portfolio.head())
print(prices.head())
print(vnindex.head())

portfolio.columns = portfolio.columns.str.lower().str.strip()

portfolio["date"] = pd.to_datetime(portfolio["date"]).dt.normalize()
portfolio["ticker"] = portfolio["ticker"].astype(str).str.upper().str.strip()
portfolio["weight"] = pd.to_numeric(portfolio["weight"], errors="coerce")

portfolio = portfolio.dropna(subset=["date", "ticker", "weight"])

# Normalize weights within each weekly portfolio
portfolio["weight_norm"] = (
    portfolio["weight"] / portfolio.groupby("date")["weight"].transform("sum")
)

portfolio = portfolio.sort_values(["date", "ticker"]).reset_index(drop=True)

print(portfolio.head())
print(portfolio.groupby("date")["weight_norm"].sum().head())

prices.columns = prices.columns.str.lower().str.strip()

prices["date"] = pd.to_datetime(prices["date"]).dt.normalize()
prices["ticker"] = prices["ticker"].astype(str).str.upper().str.strip()

for col in ["open", "high", "low", "close", "volume"]:
    if col in prices.columns:
        prices[col] = (
            prices[col]
            .astype(str)
            .str.replace(",", "", regex=False)
        )
        prices[col] = pd.to_numeric(prices[col], errors="coerce")

prices = prices.dropna(subset=["date", "ticker", "close"])
prices = prices.drop_duplicates(subset=["date", "ticker"], keep="last")
prices = prices.sort_values(["ticker", "date"]).reset_index(drop=True)

print(prices.head())
print(prices.dtypes)

vnindex.columns = vnindex.columns.str.lower().str.strip()

vnindex = vnindex.rename(columns={"time": "date"})

vnindex["date"] = pd.to_datetime(vnindex["date"]).dt.normalize()

vnindex["price"] = (
    vnindex["price"]
    .astype(str)
    .str.replace(",", "", regex=False)
)

vnindex["price"] = pd.to_numeric(vnindex["price"], errors="coerce")

vnindex = vnindex.dropna(subset=["date", "price"])
vnindex = vnindex.drop_duplicates(subset=["date"], keep="last")
vnindex = vnindex.sort_values("date").reset_index(drop=True)

print(vnindex.head())

rebalance_dates = (
    portfolio["date"]
    .drop_duplicates()
    .sort_values()
    .reset_index(drop=True)
)

next_date_map = {
    rebalance_dates.iloc[i]: rebalance_dates.iloc[i + 1]
    for i in range(len(rebalance_dates) - 1)
}

portfolio["exit_date"] = portfolio["date"].map(next_date_map)

# Drop the final portfolio because it has no future exit date
portfolio = portfolio.dropna(subset=["exit_date"])

print(portfolio[["date", "exit_date"]].drop_duplicates().head())

price_close = prices[["date", "ticker", "close"]].copy()

entry_prices = price_close.rename(columns={
    "close": "entry_price"
})

exit_prices = price_close.rename(columns={
    "date": "exit_date",
    "close": "exit_price"
})

bt = portfolio.merge(
    entry_prices,
    on=["date", "ticker"],
    how="left"
)

bt = bt.merge(
    exit_prices,
    on=["exit_date", "ticker"],
    how="left"
)

bt["stock_return"] = bt["exit_price"] / bt["entry_price"] - 1

print(bt.head())

missing_entry = bt[bt["entry_price"].isna()]
missing_exit = bt[bt["exit_price"].isna()]

print("Missing entry prices:", len(missing_entry))
print("Missing exit prices:", len(missing_exit))

print(missing_entry[["date", "ticker", "entry_price"]].head(20))
print(missing_exit[["exit_date", "ticker", "exit_price"]].head(20))

bt_valid = bt.dropna(subset=["entry_price", "exit_price", "stock_return"]).copy()

coverage = (
    bt_valid
    .groupby(["date", "exit_date"], as_index=False)
    .agg(
        weight_coverage=("weight_norm", "sum"),
        number_of_stocks=("ticker", "count")
    )
)

print(coverage.head())
print(coverage["weight_coverage"].describe())

bt_valid["weight_used"] = (
    bt_valid["weight_norm"] /
    bt_valid.groupby("date")["weight_norm"].transform("sum")
)

bt_valid["weighted_return"] = (
    bt_valid["weight_used"] * bt_valid["stock_return"]
)

portfolio_returns = (
    bt_valid
    .groupby(["date", "exit_date"], as_index=False)
    .agg(
        portfolio_return=("weighted_return", "sum"),
        number_of_stocks=("ticker", "count"),
        original_weight_coverage=("weight_norm", "sum")
    )
)

print(portfolio_returns.head())

# Make a clean VNINDEX table
vn = vnindex.copy()

vn.columns = vn.columns.str.lower().str.strip()

# Safety rename in case you rerun from original data
vn = vn.rename(columns={
    "time": "date",
    "price": "close"
})

vn["date"] = pd.to_datetime(vn["date"]).dt.normalize()
vn["close"] = pd.to_numeric(vn["close"], errors="coerce")

vn = vn.dropna(subset=["date", "close"])
vn = vn.drop_duplicates(subset=["date"], keep="last")
vn = vn.sort_values("date").reset_index(drop=True)

# Make sure portfolio_returns dates are clean
portfolio_returns["date"] = pd.to_datetime(portfolio_returns["date"]).dt.normalize()
portfolio_returns["exit_date"] = pd.to_datetime(portfolio_returns["exit_date"]).dt.normalize()

# Create VNINDEX entry and exit tables
vn_entry = vn[["date", "close"]].rename(columns={
    "close": "vnindex_entry"
})

vn_exit = vn[["date", "close"]].rename(columns={
    "date": "exit_date",
    "close": "vnindex_exit"
})

# Remove old columns if you already ran this cell before
portfolio_returns = portfolio_returns.drop(
    columns=[
        "vnindex_entry",
        "vnindex_exit",
        "vnindex_return",
        "active_return",
        "beat_vnindex"
    ],
    errors="ignore"
)

# Merge VNINDEX entry price
portfolio_returns = portfolio_returns.merge(
    vn_entry,
    on="date",
    how="left"
)

# Merge VNINDEX exit price
portfolio_returns = portfolio_returns.merge(
    vn_exit,
    on="exit_date",
    how="left"
)

# Calculate benchmark and active returns
portfolio_returns["vnindex_return"] = (
    portfolio_returns["vnindex_exit"] /
    portfolio_returns["vnindex_entry"] - 1
)

portfolio_returns["active_return"] = (
    portfolio_returns["portfolio_return"] -
    portfolio_returns["vnindex_return"]
)

portfolio_returns["beat_vnindex"] = (
    portfolio_returns["active_return"] > 0
)

portfolio_returns.head()

active = portfolio_returns["active_return"].dropna()

t_stat, p_value = stats.ttest_1samp(active, 0)

summary = pd.DataFrame({
    "Metric": [
        "Number of weekly portfolios",
        "Mean portfolio return",
        "Mean VNINDEX return",
        "Mean active return",
        "Median active return",
        "Win rate versus VNINDEX",
        "t-statistic of active return",
        "p-value",
        "Average number of stocks",
        "Average original weight coverage"
    ],
    "Value": [
        len(portfolio_returns),
        portfolio_returns["portfolio_return"].mean(),
        portfolio_returns["vnindex_return"].mean(),
        active.mean(),
        active.median(),
        portfolio_returns["beat_vnindex"].mean(),
        t_stat,
        p_value,
        portfolio_returns["number_of_stocks"].mean(),
        portfolio_returns["original_weight_coverage"].mean()
    ]
})

summary

import matplotlib.pyplot as plt

portfolio_returns = portfolio_returns.sort_values("date").reset_index(drop=True)

portfolio_returns["cum_portfolio"] = (
    1 + portfolio_returns["portfolio_return"]
).cumprod() - 1

portfolio_returns["cum_vnindex"] = (
    1 + portfolio_returns["vnindex_return"]
).cumprod() - 1

plt.figure(figsize=(12, 6))
plt.plot(portfolio_returns["date"], portfolio_returns["cum_portfolio"], label="Portfolio")
plt.plot(portfolio_returns["date"], portfolio_returns["cum_vnindex"], label="VNINDEX")
plt.legend()
plt.title("Cumulative Return: Portfolio vs VNINDEX")
plt.xlabel("Date")
plt.ylabel("Cumulative Return")
plt.grid(True)
plt.show()

output_file = "portfolio_vs_vnindex_results.xlsx"

with pd.ExcelWriter(output_file) as writer:
    portfolio_returns.to_excel(writer, sheet_name="weekly_results", index=False)
    summary.to_excel(writer, sheet_name="summary", index=False)
    bt_valid.to_excel(writer, sheet_name="stock_level_returns", index=False)

files.download(output_file)